# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fishing
email:
description: >- # this means to ignore newlines until "baseurl:"
  Hella Great!
# twitter_username: username
# github_username: username
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /_pages/posts/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jingchi Ma"
  avatar : "/assets/images/wokung.jpeg"
  bio    : "Am I A Software Engineer?"
  # links:
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/"

# footer:
#   links:

defaults:
  # collections other than _posts
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      comments: true
      sidebar:
        nav: "collection_index"
      toc: true
  # _posts
  - scope:
      path: "collections/_posts"
      type: posts
    values:
      sidebar:
        nav: "post_index"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      toc: false
  # homepage
  - scope:
      path: "index.html"
    values:
      toc: false

category_archive:
  type: liquid
  path: /posts/categories/
tag_archive:
  type: liquid
  path: /posts/tags/

collections_dir: collections

collections:
  animes:
    output: true
    permalink: /animes/:path/
  projects:
    output: true
    permalink: /projects/:path/
  algorithms:
    output: true
    permalink: /algorithms/:path/
  dataStructures:
    output: true
    permalink: /dataStructures/:path/
  videoGames:
    output: true
    permalink: /videoGames/:path/
